import {
  Info,
  Target,
  Lightbulb,
  Users,
  Rocket,
  BookOpen,
  Code2,
  ShieldCheck,
  FlaskConical,
  TrendingUp,
  AlertCircle,
  ArrowRight,
} from 'lucide-react';
import type { PageId } from '../types';
import { SectionTitle, Card, Badge } from '../components/ui';

interface AboutProps {
  onNavigate: (page: PageId) => void;
}

const TARGET_USERS = [
  'Professionals',
  'Students',
  'Interns',
  'Entrepreneurs',
  'Administrative teams',
  'Small businesses',
];

const FEATURES_LIST = [
  { name: 'Smart Email Generator', description: 'AI-assisted email drafting with tone, purpose, and audience controls.' },
  { name: 'Meeting Notes Summarizer', description: 'Structured summaries with action items, decisions, and key points.' },
  { name: 'AI Task Planner', description: 'Prioritized task planning with timelines and productivity recommendations.' },
  { name: 'AI Research Assistant', description: 'Structured research briefs with insights, findings, and recommendations.' },
  { name: 'AI Chatbot', description: 'Interactive workplace assistant with quick prompts and chat history.' },
  { name: 'Prompt Engineering Lab', description: 'RTC CO framework teaching tool with prompt testing and comparison.' },
];

const AI_TOOLS = [
  'Large Language Model (LLM) for text generation',
  'Prompt engineering using the RTC CO framework',
  'Structured output formatting for consistency',
  'Mock/demo response system for prototyping',
  'Secure edge function architecture for future API integration',
];

const LEARNING_OBJECTIVES = [
  { icon: Lightbulb, title: 'Introduction to AI', description: 'The app demonstrates practical AI through email generation, summarization, planning, and research — showing how AI can handle real workplace tasks.' },
  { icon: TrendingUp, title: 'Maximizing Productivity with AI Tools', description: 'Each feature reduces repetitive work: drafting emails, processing notes, organizing tasks, and creating research briefs — all with structured AI assistance.' },
  { icon: FlaskConical, title: 'Prompt Engineering', description: 'The Prompt Lab teaches the RTC CO framework (Role, Task, Context, Constraints, Output) with before-and-after examples and a hands-on testing area.' },
  { icon: ShieldCheck, title: 'Responsible AI', description: 'A dedicated page covers verification, protection, questioning, and ownership — plus known limitations and a human validation workflow.' },
  { icon: Rocket, title: 'Staying Ahead of the AI Curve', description: 'A five-phase roadmap shows the path from prototype to enterprise, demonstrating awareness of where AI productivity tools are heading.' },
];

const ROADMAP = [
  { phase: 'Phase 1', title: 'Prototype', status: 'Current', description: 'Working demo with mock AI responses and full UI.' },
  { phase: 'Phase 2', title: 'Real LLM Integration', status: 'Planned', description: 'Connect to a live language model via secure edge functions.' },
  { phase: 'Phase 3', title: 'Calendar & Email Integration', status: 'Planned', description: 'Sync with calendars and email clients for real workflows.' },
  { phase: 'Phase 4', title: 'Live Research with Citations', status: 'Planned', description: 'Verified web research with traceable citations.' },
  { phase: 'Phase 5', title: 'Analytics & Enterprise', status: 'Planned', description: 'Productivity analytics and enterprise deployment features.' },
];

const LIMITATIONS = [
  'AI responses are simulated for the prototype — not generated by a live LLM.',
  'No live web research is performed; research briefs are based on general knowledge.',
  'No real data persistence; all data is demo/prototype data.',
  'No authentication; the app works without sign-in for demonstration.',
  'No real calendar or email integration in the prototype.',
];

const FUTURE_IMPROVEMENTS = [
  'Connect to a real LLM API via secure Supabase Edge Functions.',
  'Add user authentication and personalized workspaces.',
  'Integrate with calendar and email platforms.',
  'Enable live web research with verified citations.',
  'Add productivity analytics and reporting dashboards.',
  'Support team collaboration and shared workflows.',
];

export default function About({ onNavigate }: AboutProps) {
  return (
    <div className="animate-fade-in">
      <SectionTitle
        title="About the Project"
        subtitle="Why WorkMate AI exists and what it demonstrates."
        icon={<Info className="w-6 h-6" />}
      />

      {/* Why WorkMate AI */}
      <Card className="p-6 lg:p-8 mb-6">
        <div className="flex items-center gap-2 mb-4">
          <Target className="w-5 h-5 text-violet-400" />
          <h2 className="text-xl font-bold text-white">Why WorkMate AI?</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <h3 className="text-sm font-semibold text-slate-300 mb-2">The Problem</h3>
            <p className="text-sm text-slate-400 leading-relaxed">
              Professionals spend significant amounts of time on repetitive activities such as email
              drafting, meeting documentation, task planning and research. These tasks are necessary
              but consume time that could be spent on higher-value work.
            </p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-slate-300 mb-2">The Solution</h3>
            <p className="text-sm text-slate-400 leading-relaxed">
              WorkMate AI combines AI-assisted workflows with human oversight to reduce repetitive work
              and create structured starting points for professionals. The AI handles the first draft;
              the human handles the final decision.
            </p>
          </div>
        </div>
      </Card>

      {/* Target users */}
      <Card className="p-6 mb-6">
        <div className="flex items-center gap-2 mb-4">
          <Users className="w-5 h-5 text-violet-400" />
          <h3 className="text-sm font-semibold text-white">Target Users</h3>
        </div>
        <div className="flex flex-wrap gap-2">
          {TARGET_USERS.map((user) => (
            <Badge key={user} color="violet">{user}</Badge>
          ))}
        </div>
      </Card>

      {/* Features */}
      <div className="mb-6">
        <h3 className="text-sm font-semibold text-slate-300 mb-4">Features</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {FEATURES_LIST.map((feature) => (
            <div key={feature.name} className="rounded-xl bg-ink-850/50 border border-ink-600 p-4">
              <h4 className="text-sm font-semibold text-white mb-1">{feature.name}</h4>
              <p className="text-xs text-slate-400 leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* AI tools & methodology */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <Card className="p-6">
          <div className="flex items-center gap-2 mb-4">
            <Code2 className="w-5 h-5 text-violet-400" />
            <h3 className="text-sm font-semibold text-white">AI Tools & Technology</h3>
          </div>
          <ul className="space-y-2">
            {AI_TOOLS.map((tool) => (
              <li key={tool} className="flex items-start gap-2 text-sm text-slate-400">
                <span className="w-1.5 h-1.5 rounded-full bg-violet-400 shrink-0 mt-2" />
                {tool}
              </li>
            ))}
          </ul>
        </Card>

        <Card className="p-6">
          <div className="flex items-center gap-2 mb-4">
            <FlaskConical className="w-5 h-5 text-violet-400" />
            <h3 className="text-sm font-semibold text-white">Prompt Engineering Methodology</h3>
          </div>
          <p className="text-sm text-slate-400 leading-relaxed mb-3">
            WorkMate AI uses the <span className="text-violet-350 font-semibold">RTC CO</span> framework:
          </p>
          <ul className="space-y-2">
            <li className="flex items-start gap-2 text-sm text-slate-400"><span className="text-violet-350 font-bold">R</span> — Role: Define who the AI acts as</li>
            <li className="flex items-start gap-2 text-sm text-slate-400"><span className="text-violet-350 font-bold">T</span> — Task: Define what needs to be done</li>
            <li className="flex items-start gap-2 text-sm text-slate-400"><span className="text-violet-350 font-bold">C</span> — Context: Provide relevant information</li>
            <li className="flex items-start gap-2 text-sm text-slate-400"><span className="text-violet-350 font-bold">C</span> — Constraints: Set rules and limitations</li>
            <li className="flex items-start gap-2 text-sm text-slate-400"><span className="text-violet-350 font-bold">O</span> — Output: Define the response format</li>
          </ul>
        </Card>
      </div>

      {/* Responsible AI practices */}
      <Card className="p-6 mb-6">
        <div className="flex items-center gap-2 mb-4">
          <ShieldCheck className="w-5 h-5 text-violet-400" />
          <h3 className="text-sm font-semibold text-white">Responsible AI Practices</h3>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div className="text-sm text-slate-400 flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0 mt-2" />
            AI never invents names, dates, or facts not provided by the user
          </div>
          <div className="text-sm text-slate-400 flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0 mt-2" />
            All outputs clearly labeled as AI-generated
          </div>
          <div className="text-sm text-slate-400 flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0 mt-2" />
            Missing information displayed as "Not specified"
          </div>
          <div className="text-sm text-slate-400 flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0 mt-2" />
            Disclaimers on every AI tool page
          </div>
          <div className="text-sm text-slate-400 flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0 mt-2" />
            No API keys exposed in frontend code
          </div>
          <div className="text-sm text-slate-400 flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0 mt-2" />
            Dedicated Responsible AI page with principles and workflow
          </div>
        </div>
        <button onClick={() => onNavigate('responsible-ai')} className="btn-ghost mt-4 text-xs">
          View Responsible AI page <ArrowRight className="w-3 h-3" />
        </button>
      </Card>

      {/* Learning objectives */}
      <div className="mb-6">
        <h3 className="text-sm font-semibold text-slate-300 mb-4">Learning Objectives Demonstrated</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {LEARNING_OBJECTIVES.map((obj) => {
            const Icon = obj.icon;
            return (
              <div key={obj.title} className="rounded-xl bg-ink-850/50 border border-ink-600 p-4">
                <div className="flex items-start gap-3">
                  <div className="w-9 h-9 rounded-lg bg-violet-500/10 border border-violet-500/20 flex items-center justify-center shrink-0">
                    <Icon className="w-4 h-4 text-violet-400" />
                  </div>
                  <div>
                    <h4 className="text-sm font-semibold text-white mb-1">{obj.title}</h4>
                    <p className="text-xs text-slate-400 leading-relaxed">{obj.description}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Roadmap */}
      <div className="mb-6">
        <h3 className="text-sm font-semibold text-slate-300 mb-4">Future Roadmap</h3>
        <div className="relative">
          <div className="absolute left-4 top-0 bottom-0 w-px bg-ink-600 hidden sm:block" />
          <div className="space-y-3">
            {ROADMAP.map((item) => (
              <div key={item.phase} className="relative flex items-start gap-4 sm:pl-12">
                <div className="hidden sm:flex absolute left-0 top-1 w-8 h-8 rounded-full bg-ink-800 border-2 border-violet-500/30 items-center justify-center">
                  <span className="text-[10px] font-bold text-violet-350">{item.phase.split(' ')[1]}</span>
                </div>
                <div className="glass-card p-4 flex-1">
                  <div className="flex items-center justify-between mb-1">
                    <h4 className="text-sm font-semibold text-white">{item.title}</h4>
                    <span className={`chip ${
                      item.status === 'Current'
                        ? 'bg-green-500/15 text-green-400 border border-green-500/30'
                        : 'bg-ink-700 text-slate-400 border border-ink-600'
                    }`}>
                      {item.status}
                    </span>
                  </div>
                  <p className="text-xs text-slate-400">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Limitations & Future improvements */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <Card className="p-6 border border-amber-500/20">
          <div className="flex items-center gap-2 mb-4">
            <AlertCircle className="w-5 h-5 text-amber-400" />
            <h3 className="text-sm font-semibold text-white">Current Limitations</h3>
          </div>
          <ul className="space-y-2">
            {LIMITATIONS.map((limit) => (
              <li key={limit} className="flex items-start gap-2 text-xs text-slate-400">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0 mt-1.5" />
                {limit}
              </li>
            ))}
          </ul>
        </Card>

        <Card className="p-6 border border-green-500/20">
          <div className="flex items-center gap-2 mb-4">
            <Rocket className="w-5 h-5 text-green-400" />
            <h3 className="text-sm font-semibold text-white">Future Improvements</h3>
          </div>
          <ul className="space-y-2">
            {FUTURE_IMPROVEMENTS.map((improvement) => (
              <li key={improvement} className="flex items-start gap-2 text-xs text-slate-400">
                <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0 mt-1.5" />
                {improvement}
              </li>
            ))}
          </ul>
        </Card>
      </div>

      {/* CTA */}
      <Card className="p-6 lg:p-8 text-center">
        <BookOpen className="w-8 h-8 text-violet-400 mx-auto mb-3" />
        <h3 className="text-lg font-bold text-white mb-2">Explore the Workspace</h3>
        <p className="text-sm text-slate-400 mb-5 max-w-md mx-auto">
          Try the AI tools, experiment with prompt engineering, and review the responsible AI guidelines.
        </p>
        <button onClick={() => onNavigate('dashboard')} className="btn-primary mx-auto">
          Launch Dashboard
          <ArrowRight className="w-4 h-4" />
        </button>
      </Card>
    </div>
  );
}
